In [1]:
from multiprocessing import shared_memory

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from mpmath import ones
from scipy.optimize import zeros

In [2]:
distance_values = [1.0,2.5,4.0,5.5,7.0]
distance_values

[1.0, 2.5, 4.0, 5.5, 7.0]

In [3]:
delivery_distance_1d = torch.tensor(distance_values, dtype=torch.float32)
delivery_distance_1d

tensor([1.0000, 2.5000, 4.0000, 5.5000, 7.0000])

In [4]:
delivery_distance_1d.shape

torch.Size([5])

In [5]:
delivery_distance_2d = delivery_distance_1d.reshape(-1,1)
delivery_distance_2d

tensor([[1.0000],
        [2.5000],
        [4.0000],
        [5.5000],
        [7.0000]])

In [6]:
single_feature_model = nn.Linear(1, 1)
outputs = single_feature_model(delivery_distance_2d)
outputs.shape

torch.Size([5, 1])

In [7]:
multi_feature_values = [
    [1.0,2.0,3.0],
    [2.0,1.5,4.0],
    [4.0,3.0,2.5],
    [5.0,6.0,1.0],
    [7.0,4.5,3.5]
]
multi_feature_values

[[1.0, 2.0, 3.0],
 [2.0, 1.5, 4.0],
 [4.0, 3.0, 2.5],
 [5.0, 6.0, 1.0],
 [7.0, 4.5, 3.5]]

In [8]:
multi_feature = torch.tensor(multi_feature_values, dtype=torch.float32)
multi_feature

tensor([[1.0000, 2.0000, 3.0000],
        [2.0000, 1.5000, 4.0000],
        [4.0000, 3.0000, 2.5000],
        [5.0000, 6.0000, 1.0000],
        [7.0000, 4.5000, 3.5000]])

In [9]:
multi_feature.shape

torch.Size([5, 3])

In [10]:
from math import sin
try:
    outputs = single_feature_model(multi_feature)
except RuntimeError as e:
    print("\nRuntimeError")
    print(e)


RuntimeError
mat1 and mat2 shapes cannot be multiplied (5x3 and 1x1)


In [11]:
distances_values = [1.0,2.5,4.0,5.5,7.0]

broken_distances = torch.tensor(distances_values, dtype=torch.float32)
broken_distances.shape

torch.Size([5])

In [12]:
try:
    outputs = single_feature_model(broken_distances)
except Exception as e:
    print("\nError")
    print(e)


Error
mat1 and mat2 shapes cannot be multiplied (1x5 and 1x1)


In [13]:
broken_distances = broken_distances.reshape(-1,1)
broken_distances.shape

torch.Size([5, 1])

In [14]:
raw_data = [
    [1200.0, 3.0],
    [1500.0, 4.0],
    [800.0, 2.0],
    [2500.0, 5.0]
]
house_data = torch.tensor(raw_data, dtype=torch.float32)
house_data.shape

torch.Size([4, 2])

In [15]:
two_feature_model = nn.Linear(2,1)
house_outputs = two_feature_model(house_data)
house_outputs.shape

torch.Size([4, 1])

In [16]:
wrong_model = nn.Linear(1,1)
house_data.shape

torch.Size([4, 2])

In [17]:
try:
    wrong_outputs = wrong_model(house_data)
except Exception as e:
    print("\nError")
    print(e)


Error
mat1 and mat2 shapes cannot be multiplied (4x2 and 1x1)


In [18]:
int_tensor = torch.tensor([1,2,3])
float_tensor = torch.tensor([1.0,2.0,3.0])
explicit_float_tensor = torch.tensor([1,2,3], dtype=torch.float32)

In [19]:
int_tensor.dtype, float_tensor.dtype, explicit_float_tensor.dtype

(torch.int64, torch.float32, torch.float32)

In [20]:
float64_tensor = torch.tensor([1,2,3], dtype=torch.float64)
int8_tensor = torch.tensor([1,2,3], dtype=torch.uint8)

In [21]:
float64_tensor.dtype, int8_tensor.dtype

(torch.float64, torch.uint8)

In [22]:
result = int_tensor + float_tensor
result, result.dtype

(tensor([2., 4., 6.]), torch.float32)

In [23]:
list_tensor = torch.tensor([[1.0,2.0], [3.0,4.0]])
list_tensor

tensor([[1., 2.],
        [3., 4.]])

In [24]:
np_array = np.array([[10,20],[30,40]], dtype=np.float32)
np.tensor = torch.tensor(np_array)
np_array

array([[10., 20.],
       [30., 40.]], dtype=float32)

In [25]:
zeros_tensor = torch.zeros(2,2)
ones_tensor = torch.ones(2,2)
random_tensor = torch.rand(2,2)

In [26]:
zeros_tensor, ones_tensor, random_tensor

(tensor([[0., 0.],
         [0., 0.]]),
 tensor([[1., 1.],
         [1., 1.]]),
 tensor([[0.6516, 0.3042],
         [0.4506, 0.5563]]))

In [27]:
shared_array = np.array([1.0,2.0,3.0], dtype=np.float32)
shared_tensor = torch.from_numpy(shared_array) ##**

print("Before Numpy change: ")
print("shared_array: ", shared_array)
print("shared_tensor: ", shared_tensor)

shared_array[0] = 99.0

print("\nAfter Numpy change: ")
print("shared_array: ", shared_array)
print("shared_tensor: ", shared_tensor)

Before Numpy change: 
shared_array:  [1. 2. 3.]
shared_tensor:  tensor([1., 2., 3.])

After Numpy change: 
shared_array:  [99.  2.  3.]
shared_tensor:  tensor([99.,  2.,  3.])


In [28]:
single_house = torch.tensor([2100.0,4.0], dtype=torch.float32)
single_house.shape

torch.Size([2])

In [29]:
single_house_batch = single_house.unsqueeze(0)
single_house_batch.shape

torch.Size([1, 2])

In [30]:
manual_batch = torch.tensor([[2100.0,4.0]], dtype=torch.float32)
manual_batch.shape

torch.Size([1, 2])

In [31]:
single_prediction = two_feature_model(single_house_batch)
single_prediction

tensor([[-1292.0837]], grad_fn=<AddmmBackward0>)

In [32]:
single_prediction.shape

torch.Size([1, 1])

In [33]:
print(single_prediction)

tensor([[-1292.0837]], grad_fn=<AddmmBackward0>)


In [34]:
single_prediction.item()

-1292.083740234375

In [35]:
batch_prediction = two_feature_model(house_data)
batch_prediction

tensor([[ -738.5331],
        [ -923.4825],
        [ -492.1502],
        [-1538.4667]], grad_fn=<AddmmBackward0>)

In [36]:
batch_prediction.shape

torch.Size([4, 1])

In [38]:
batch_prediction.squeeze().shape

torch.Size([4])

In [39]:
house_data[0]

tensor([1200.,    3.])

In [40]:
house_data[:2]

tensor([[1200.,    3.],
        [1500.,    4.]])

In [41]:
house_data[:,0]

tensor([1200., 1500.,  800., 2500.])

In [42]:
house_data[:,1]

tensor([3., 4., 2., 5.])

In [43]:
batch_prediction[0]

tensor([-738.5331], grad_fn=<SelectBackward0>)

In [44]:
batch_prediction[0].item()

-738.5331420898438

In [ ]:
print("delivery distances shape:", delivery_distances.shape, "| dtype:", delivery_distances.dtype)
print("house_data shape    :", house_data.shape, "| dtype:", house_data.dtype)
print("single_house_batch shape:", single_house_batch.shape, "| dtype:", single_house_batch.dtype)