In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

In [4]:
distance_values = [1.0,2.5,4.0,5.5,7.0]
distance_values

[1.0, 2.5, 4.0, 5.5, 7.0]

In [5]:
delivery_distance_1d = torch.tensor(distance_values, dtype=torch.float32)
delivery_distance_1d

tensor([1.0000, 2.5000, 4.0000, 5.5000, 7.0000])

In [6]:
delivery_distance_1d.shape

torch.Size([5])

In [8]:
delivery_distance_2d = delivery_distance_1d.reshape(-1,1)
delivery_distance_2d

tensor([[1.0000],
        [2.5000],
        [4.0000],
        [5.5000],
        [7.0000]])

In [10]:
single_feature_model = nn.Linear(1, 1)
outputs = single_feature_model(delivery_distance_2d)
outputs.shape

torch.Size([5, 1])

In [12]:
multi_feature_values = [
    [1.0,2.0,3.0],
    [2.0,1.5,4.0],
    [4.0,3.0,2.5],
    [5.0,6.0,1.0],
    [7.0,4.5,3.5]
]
multi_feature_values

[[1.0, 2.0, 3.0],
 [2.0, 1.5, 4.0],
 [4.0, 3.0, 2.5],
 [5.0, 6.0, 1.0],
 [7.0, 4.5, 3.5]]

In [13]:
multi_feature = torch.tensor(multi_feature_values, dtype=torch.float32)
multi_feature

tensor([[1.0000, 2.0000, 3.0000],
        [2.0000, 1.5000, 4.0000],
        [4.0000, 3.0000, 2.5000],
        [5.0000, 6.0000, 1.0000],
        [7.0000, 4.5000, 3.5000]])

In [14]:
multi_feature.shape

torch.Size([5, 3])

In [15]:
from math import sin
try:
    outputs = single_feature_model(multi_feature)
except RuntimeError as e:
    print("\nRuntimeError")
    print(e)


RuntimeError
mat1 and mat2 shapes cannot be multiplied (5x3 and 1x1)
