In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

In [2]:
distance_values = [1.0,2.5,4.0,5.5,7.0]
distance_values

[1.0, 2.5, 4.0, 5.5, 7.0]

In [3]:
delivery_distance_1d = torch.tensor(distance_values, dtype=torch.float32)
delivery_distance_1d

tensor([1.0000, 2.5000, 4.0000, 5.5000, 7.0000])

In [4]:
delivery_distance_1d.shape

torch.Size([5])

In [5]:
delivery_distance_2d = delivery_distance_1d.reshape(-1,1)
delivery_distance_2d

tensor([[1.0000],
        [2.5000],
        [4.0000],
        [5.5000],
        [7.0000]])

In [6]:
single_feature_model = nn.Linear(1, 1)
outputs = single_feature_model(delivery_distance_2d)
outputs.shape

torch.Size([5, 1])

In [7]:
multi_feature_values = [
    [1.0,2.0,3.0],
    [2.0,1.5,4.0],
    [4.0,3.0,2.5],
    [5.0,6.0,1.0],
    [7.0,4.5,3.5]
]
multi_feature_values

[[1.0, 2.0, 3.0],
 [2.0, 1.5, 4.0],
 [4.0, 3.0, 2.5],
 [5.0, 6.0, 1.0],
 [7.0, 4.5, 3.5]]

In [8]:
multi_feature = torch.tensor(multi_feature_values, dtype=torch.float32)
multi_feature

tensor([[1.0000, 2.0000, 3.0000],
        [2.0000, 1.5000, 4.0000],
        [4.0000, 3.0000, 2.5000],
        [5.0000, 6.0000, 1.0000],
        [7.0000, 4.5000, 3.5000]])

In [9]:
multi_feature.shape

torch.Size([5, 3])

In [10]:
from math import sin
try:
    outputs = single_feature_model(multi_feature)
except RuntimeError as e:
    print("\nRuntimeError")
    print(e)


RuntimeError
mat1 and mat2 shapes cannot be multiplied (5x3 and 1x1)


In [14]:
distances_values = [1.0,2.5,4.0,5.5,7.0]

broken_distances = torch.tensor(distances_values, dtype=torch.float32)
broken_distances.shape

torch.Size([5])

In [15]:
try:
    outputs = single_feature_model(broken_distances)
except Exception as e:
    print("\nError")
    print(e)


Error
mat1 and mat2 shapes cannot be multiplied (1x5 and 1x1)


In [17]:
broken_distances = broken_distances.reshape(-1,1)
broken_distances.shape

torch.Size([5, 1])

In [18]:
raw_data = [
    [1200.0, 3.0],
    [1500.0, 4.0],
    [800.0, 2.0],
    [2500.0, 5.0]
]
house_data = torch.tensor(raw_data, dtype=torch.float32)
house_data.shape

torch.Size([4, 2])

In [19]:
two_feature_model = nn.Linear(2,1)
house_outputs = two_feature_model(house_data)
house_outputs.shape

torch.Size([4, 1])

In [20]:
wrong_model = nn.Linear(1,1)
house_data.shape

torch.Size([4, 2])

In [21]:
try:
    wrong_outputs = wrong_model(house_data)
except Exception as e:
    print("\nError")
    print(e)


Error
mat1 and mat2 shapes cannot be multiplied (4x2 and 1x1)
