In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import pandas as pd
from numpy import dtypes

torch.manual_seed(42)

In [5]:
predictions = torch.tensor([[6.0],[3.0]], dtype=torch.float)
targets = torch.tensor([[4.0],[5.0]], dtype=torch.float)

raw_errors = predictions - targets
squared_error = raw_errors ** 2
manual_mse = squared_error.mean()

In [6]:
raw_errors

tensor([[ 2.],
        [-2.]])

In [7]:
squared_error

tensor([[4.],
        [4.]])

In [8]:
manual_mse

tensor(4.)

In [9]:
mse_loss_function = nn.MSELoss()
pytorch_mse = mse_loss_function(predictions, targets)
pytorch_mse

tensor(4.)

In [12]:
print("Predictions: ")
print(predictions.squeeze())
print("Targets: ")
print(targets.squeeze())
print("Raw errors: ")
print(raw_errors.squeeze())
print("Squared error: ")
print(squared_error.squeeze())
print("manual mse: ")
print(manual_mse)
print("Pytorch mse: ")
print(pytorch_mse)

Predictions: 
tensor([6., 3.])
Targets: 
tensor([4., 5.])
Raw errors: 
tensor([ 2., -2.])
Squared error: 
tensor([4., 4.])
manual mse: 
tensor(4.)
Pytorch mse: 
tensor(4.)


In [13]:
small_error = torch.tensor([1.0])
big_error = torch.tensor([10.0])

print("Small error: ", small_error.item(), "squared: ", (small_error**2).item())
print("Large error: ", big_error.item(), "squared: ", (big_error**2).item())

Small error:  1.0 squared:  1.0
Large error:  10.0 squared:  100.0
